// valkyrin-core/src/ast.rs
use std::fs;
use tree_sitter::{Node, Parser};

pub struct CodeMerger {
    pub language: tree_sitter::Language,
}

impl CodeMerger {
    pub fn new_go() -> Self {
        Self {
            // Fix 1: Use the modern constant and convert it
            language: tree_sitter_go::LANGUAGE.into(),
        }
    }

    /// Reads an existing file and extracts all custom developer code blocks.
    pub fn extract_custom_zones(&self, filepath: &str) -> Option<String> {
        let source_code = fs::read_to_string(filepath).ok()?;

        let mut parser = Parser::new();
        // Fix 2: Pass the memory reference using &
        parser
            .set_language(&self.language)
            .expect("Error loading Go grammar");

        let tree = parser.parse(&source_code, None)?;
        let root_node = tree.root_node();

        self.find_protected_zone(root_node, &source_code)
    }

    fn find_protected_zone(&self, node: Node, source: &str) -> Option<String> {
        let text = &source[node.start_byte()..node.end_byte()];

        if text.contains("valkyrin:custom_methods_start") {
            let start = text.find("valkyrin:custom_methods_start")? + 29;
            let end = text.find("valkyrin:custom_methods_end")?;
            return Some(text[start..end].trim().to_string());
        }

        // Fix 3: Explicitly cast the usize down to a u32 for the AST API
        for i in 0..node.child_count() as u32 {
            if let Some(custom_code) = self.find_protected_zone(node.child(i).unwrap(), source) {
                return Some(custom_code);
            }
        }
        None
    }

    /// Generates the final output file by combining fresh schemas with extracted code.
    pub fn stitch_and_write(
        &self,
        filepath: &str,
        generated_schema_code: String,
        extracted_custom_code: Option<String>,
    ) -> Result<(), std::io::Error> {
        let mut final_file = String::new();
        final_file.push_str("// Code generated by Valkyrin. DO NOT EDIT BASE STRUCTS.\n\n");
        final_file.push_str(&generated_schema_code);

        final_file.push_str("\n\n// ==============================================\n");
        final_file.push_str("// valkyrin:custom_methods_start\n");
        final_file.push_str("// DO NOT DELETE. Add your custom methods below.\n");
        final_file.push_str("// ==============================================\n\n");

        if let Some(custom_code) = extracted_custom_code {
            final_file.push_str(&custom_code);
        }

        final_file.push_str("\n\n// valkyrin:custom_methods_end\n");
        final_file.push_str("// ==============================================\n");

        fs::write(filepath, final_file)
    }
}
