// valkyrin-core/src/ast.rs
use crate::codegen::TargetBackend;
use std::fs;
use tree_sitter::{Node, Parser};

pub struct CodeMerger {
    pub comment_prefix: &'static str,
}

impl CodeMerger {
    /// Creates a new CodeMerger for the given backend.
    /// Maps each backend to its appropriate comment syntax.
    pub fn new(backend: &TargetBackend) -> Self {
        let comment_prefix = match backend {
            // Python uses # for comments
            TargetBackend::PythonSqlAlchemy | TargetBackend::PythonSqlModel => "#",
            // Everything else uses //
            TargetBackend::GoGorm
            | TargetBackend::GoEnt
            | TargetBackend::RustDiesel
            | TargetBackend::RustSeaOrm
            | TargetBackend::JavaScriptSequelize
            | TargetBackend::JavaScriptTypeOrm
            | TargetBackend::TypeScriptPrisma
            | TargetBackend::TypeScriptTypeOrm
            | TargetBackend::TypeScriptValkyrin => "//",
        };
        Self { comment_prefix }
    }

    /// Creates a CodeMerger for Go (backward compatibility).
    pub fn new_go() -> Self {
        Self {
            comment_prefix: "//",
        }
    }

    /// Reads an existing file and extracts all custom developer code blocks.
    /// Uses tree-sitter for Go and Python, pure string-based fallback for others.
    pub fn extract_custom_zones(&self, filepath: &str, backend: &TargetBackend) -> Option<String> {
        match backend {
            // Use tree-sitter for Go and Python (we have the grammars)
            TargetBackend::GoGorm | TargetBackend::GoEnt => {
                self.extract_custom_zones_tree_sitter(filepath, tree_sitter_go::LANGUAGE.into())
            }
            TargetBackend::PythonSqlAlchemy | TargetBackend::PythonSqlModel => {
                self.extract_custom_zones_tree_sitter(filepath, tree_sitter_python::LANGUAGE.into())
            }
            // Use string-based fallback for Rust, JS, TS, Prisma
            _ => self.extract_custom_zones_string_based(filepath),
        }
    }

    /// Tree-sitter based extraction for languages where we have grammars.
    fn extract_custom_zones_tree_sitter(
        &self,
        filepath: &str,
        language: tree_sitter::Language,
    ) -> Option<String> {
        let source_code = fs::read_to_string(filepath).ok()?;

        let mut parser = Parser::new();
        parser.set_language(&language).ok()?;

        let tree = parser.parse(&source_code, None)?;
        let root_node = tree.root_node();

        self.find_protected_zone(root_node, &source_code)
    }

    /// String-based fallback for languages without tree-sitter grammars.
    /// Simply searches for the start and end markers using string operations.
    fn extract_custom_zones_string_based(&self, filepath: &str) -> Option<String> {
        let source = fs::read_to_string(filepath).ok()?;
        let start_marker = format!("{}valkyrin:custom_methods_start", self.comment_prefix);
        let end_marker = format!("{}valkyrin:custom_methods_end", self.comment_prefix);

        let start = source.find(&start_marker)?;
        let content_start = start + start_marker.len();
        let end = source[content_start..].find(&end_marker)?;

        Some(source[content_start..content_start + end].trim().to_string())
    }

    fn find_protected_zone(&self, node: Node, source: &str) -> Option<String> {
        let text = &source[node.start_byte()..node.end_byte()];

        if text.contains("valkyrin:custom_methods_start") {
            let start = text.find("valkyrin:custom_methods_start")? + 29;
            let end = text.find("valkyrin:custom_methods_end")?;
            return Some(text[start..end].trim().to_string());
        }

        for i in 0..node.child_count() as u32 {
            if let Some(custom_code) = self.find_protected_zone(node.child(i).unwrap(), source) {
                return Some(custom_code);
            }
        }
        None
    }

    /// Generates the final output file by combining fresh schemas with extracted code.
    /// Uses the appropriate comment syntax based on the backend.
    pub fn stitch_and_write(
        &self,
        filepath: &str,
        generated_schema_code: String,
        extracted_custom_code: Option<String>,
    ) -> Result<(), std::io::Error> {
        let mut final_file = String::new();
        final_file.push_str(&format!(
            "{} Code generated by Valkyrin. DO NOT EDIT BASE STRUCTS.\n\n",
            self.comment_prefix
        ));
        final_file.push_str(&generated_schema_code);

        let separator = format!(
            "\n\n{} ==============================================\n",
            self.comment_prefix
        );
        final_file.push_str(&separator);
        final_file.push_str(&format!(
            "{} valkyrin:custom_methods_start\n",
            self.comment_prefix
        ));
        final_file.push_str(&format!(
            "{} DO NOT DELETE. Add your custom methods below.\n",
            self.comment_prefix
        ));
        final_file.push_str(&separator);
        final_file.push('\n');

        if let Some(custom_code) = extracted_custom_code {
            final_file.push_str(&custom_code);
        }

        final_file.push_str("\n\n");
        final_file.push_str(&format!(
            "{} valkyrin:custom_methods_end\n",
            self.comment_prefix
        ));
        final_file.push_str(&separator);

        fs::write(filepath, final_file)
    }
}
