// Code generated by Valkyrin. DO NOT EDIT BASE STRUCTS.

package models

import (
	"time"
)

type Users Table struct {
}


// ==============================================
// valkyrin:custom_methods_start
// DO NOT DELETE. Add your custom methods below.
// ==============================================



// valkyrin:custom_methods_end
// ==============================================
