// Code generated by Valkyrin. DO NOT EDIT BASE STRUCTS.

package models

import (
	"time"
	"github.com/google/uuid"
)

type Users struct {
	Id uuid.UUID `gorm:"column:id;primaryKey" json:"id"`
	Name string `gorm:"column:name" json:"name"`
	Time time.Time `gorm:"column:time" json:"time"`
	Sessions_id *string `gorm:"column:sessions_id" json:"sessions_id"`
}


// ==============================================
// valkyrin:custom_methods_start
// DO NOT DELETE. Add your custom methods below.
// ==============================================

// DO NOT DELETE. Add your custom methods below.
// ==============================================



//

// valkyrin:custom_methods_end
// ==============================================
